apiVersion: apps/v1
kind: Deployment
metadata:
  name: amd-backend-auth
  namespace: amd-backend-auth
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amd-backend-auth
  template:
    metadata:
      labels:
        app: amd-backend-auth
    spec:
      nodeSelector: 
        kubernetes.io/hostname: worker1
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: amd-backend-auth
        image: ghkdtlwns987/project_amd_backend_auth
        ports:
        - containerPort: 9000
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://10.96.100.30:8761/eureka/
        - name: spring.cloud.config.uri
          value: http://10.96.100.32:8889
        - name: spring.rabbitmq.host
          value: "10.96.100.31"
        - name: spring.rabbitmq.port
          value: "5672"
      nodeName: worker1
