apiVersion: v1
kind: Service
metadata:
  name: amd-backend-auth-svc
  namespace: amd-backend-auth
spec:
  type: ClusterIP
  clusterIP: 10.96.100.34
  selector:
    app: amd-backend-auth
  ports:
  - port: 9000	# clusterPort
    targetPort: 9000 # targetPort
