apiVersion: apps/v1
kind: Deployment
metadata:
  name: amd-apigateway
  namespace: amd-apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amd-apigateway
  template:
    metadata:
      labels:
        app: amd-apigateway
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1 
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: amd-apigateway
        image: ghkdtlwns987/project_amd_apigateay
        ports:
        - containerPort: 8000
        env:
        - name: spring.rabbitmq.host
          value: "10.96.100.31"
        - name: spring.rabbitmq.port
          value: "5672"
        - name: eureka.client.serviceUrl.defaultZone
          value: http://10.96.100.30:8761/eureka/
        - name: spring.cloud.config.uri
          value: http://10.96.100.32:8889
      nodeName: worker1
