apiVersion: v1
kind: Service
metadata:
  name: amd-apigateway-svc
  namespace: amd-apigateway
spec:
  type: ClusterIP
  clusterIP: 10.96.100.33
  selector: 
    app: amd-apigateway
  ports:
  - port: 8000	# clusterPort
    targetPort: 8000 # targetPort
