apiVersion: apps/v1
kind: Deployment
metadata:
  name: amd-front
  namespace: amd-front
spec:
  replicas: 2
  selector:
    matchLabels:
      app: amd-front
  template:
    metadata:
      labels:
        app: amd-front
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: amd-front
        image: ghkdtlwns987/project_amd_public
        ports:
        - containerPort: 8888
