apiVersion: apps/v1
kind: Deployment
metadata:
  name: amd-front
  namespace: amd-front
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amd-front
  template:
    metadata:
      labels:
        app: amd-front
    spec:
      nodeSelector:
        kubernetes.io/hostname: worker1
      securityContext:
        runAsUser: 0
        runAsGroup: 0
      containers:
      - name: amd-front
        image: ghkdtlwns987/project_amd_public
        ports:
        - containerPort: 8888
        env:
        - name: eureka.client.serviceUrl.defaultZone
          value: http://10.96.100.30:8761/eureka/
        - name: spring.cloud.config.uri
          value: http://10.96.100.32:8889
        - name: spring.cloud.config.name
          value: AMD-accessList
        - name: spring.rabbitmq.host
          value: "10.96.100.31"
        - name: spring.rabbitmq.port
          value: "5672"
        - name: spring.auth.url
          value: http://10.96.100.33:8000/auth
        - name: spring.user.url
          value: http://10.96.100.33:8000/user
        - name: spring.user.dashboard
          value: http://10.96.100.33:8000/react
      nodeName: worker1 
