apiVersion: v1
kind: Service
metadata:
  name: amd-front-svc
  namespace: amd-front 
spec:
  type: NodePort
  clusterIP: 10.96.100.35
  selector: 
    app: amd-front
  ports:
  - port: 8888	# clusterPort
    targetPort: 8888 
    nodePort: 30030 # nodePort
