apiVersion: v1
kind: PersistentVolume
metadata:
  name: amd-config-pv
  labels:
    pv: amd-config-pv
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: "local-storage"
  hostPath:
    path: /mnt/config

